server:
  port: 9006
spring:
  application:
    name: crowd-pay-consumer-9006
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 192.168.159.160
  session:
    store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka

ali:
  pay:
      alipay-public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmUUrphV7Y1RbXQJeleBsmG7hom6684A5JYc69DTTOMRN4k5Qn2Vx5nB9gmk9ef2dfPgDQovnCpNz0jDfHBz9V+Kavn+10DOlTR0qJoJGWI0z83FEcn8t84KTCGTZMqWd5bYRfWW9uShvLBQFcHQFpVNjZdIRbVLIx90k/kVNAiSPmQiw6hjXAVSG0hof60xb1S7Vy0wcrON028zYgCG/79a9THKPjMHn1L2z1n4aGS/UNTd7mIYGIYcE+LAAviycsAlR+dab1qZ2VgZB/0eOexaEED+y1sHM3lBg0lAXkxMootkveoHgSKmOgSBgXOuI/FSq6NVt+5KxSDKQDgBSswIDAQAB"
      app-id: 2016102400751881
      charset: utf-8
      gateway-url: https://openapi.alipaydev.com/gateway.do
      merchant-private_key: "MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCN9R31akTFJA4P+T2OGIIi6pRM+PldcHjwejp43nt+NdEasKAV9pq+9FAgjZ+tpLXWa/sntUVxpVkZE41nEO+QD0j3twgrpIY3u3nhglMH8NCxb1I0kdjY+0Fw1S0Xl1qaD21rwyPX8/TP/KYmkLjAMByB7stJXUJAs+eab2RENGuayzW+AYVjv+PUJorTVwNGsR1Ns/hM8AEmCgDgIlbtXJIdn8dLCO2JrNjFbnjG1RbL1QrSwXJCmTuYFtCmaCNeFCnKFC90xqLef/H5VNJVydnqI+ks4iokoenjL8LDRLU03Yui3ZBw7OkoR7NMtVVBBNmQOcM5P7s6mICay7yRAgMBAAECggEADX2Bv1S9/E4U2AfDhcFmfJL2TOpMKEkL9S5oaBwceD39BSBL1kp9IjBtfOp4hjPk49+XGorrcoVYFj35bhX57iLFuGS4bg1Qg/NY/ck4wsRr0LDXiw9hIB2gdmyLwHYtsf5NU7RTr64LUcicsYWHSRxJWT+sKeim5ycxl0eGq8R69pjdvTDq8BpcEFSQaLI7JyClZ+P57FrZixsgwH4YFU1TM26Wbzl96HCxlv7gDO7xhSWevKO6VePACFoYHwLuXhSnJ4tkPEucf6faHhGEIviaEzxQoy12CRdRSJM1jGEBuCbjkOIzXv5jllih2/NcRV4WUyLL4of8l3aD43jqwQKBgQDZ8I0xBYPWmJY3Mt9uO86qZbedtlQ22GDLJzQE9Hd+JPn6a4UPf63u7ndWGQhgJOCxqhvdp1t8u3P3zpVai+pDDUK6UFUcbFoJt0Ey1TmfHos1yuJmDUpL2CepRqzWF5w4iIOWmUdk8QbxZFWwcGuFAOGy0TVHewIvp6lMNIHbLQKBgQCmv5+rW1IbRJ1rFKyHFV5tNfzDzZNPAZlTrMNpHDfk+X0LFilwXLRkTVT+0oZci6KT/MO0OpaBN6VEmuNFY9yGVkjAsLjV4crHDmdJAmpb+Lw2ylFNNwTT//ebNeTUrq1VVFzDjodcnJloMpcUQ9JvtPEuQleOGnwPdd5168N1dQKBgF78E11BLROTTyzhlDWEBW+Ig31OIOgCaDVCcc6TCZ1F2llFESoPGKxg7Evu/xKAIBnurNRvA1WakVF4jOl4v3HXzrRLHL0VkCxZ3SWdfs6VzlB0izW1JyNlIuwI7H0mrySIgulZBp+82KzOcPZEGOhP2Q5JVfJAb1R7uzKGU+5FAoGBAIOQFW6h8rpI/NsLyMQb/BC20+O5Q0zGui7m1JcOCJvErQAeUDuzKTEqQrF7cT97fJ6+g7qjrzPsr5zdiAurqsbjNSuzQ2Kdb9x2ZM+Z9Ej0i6u/HT6K9mg+QSJY919HIsN8eGRjBDHx7KflooX+rP4uCUyyU1pvUwrvuMHZbrIxAoGBAKg8r3XQx7hMdXq/tzj7Nc72ngqBNDRoB7EKKqUShbirKTOwX1Q8tXtPsHJ7888PQtkyBY3zb1g97F+Pll/2/7TIY5TiIBhx5zx4sZrRkN0JAz9rdJmI4M7Nb+zwwiMh1Uh1Bw0YGtii3mqsZMUaKZb92KaMF4M3GCnHRzW4OTos"
      notify-url: http://6t9rmg.natappfree.cc/pay/notify
      return-url: http://localhost/pay/return
      sign-type: RSA2